name: adding dep on A
on:
  push:
jobs:
  job_a:
    runs-on: ubuntu-latest
    steps:
      - run : echo "This is job A"
  job_b:
    needs: job_a
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job B"
      
